---
title: "Q1"
format: html
editor: visual
---

## **로또 당첨번호 크롤링 후 시각화**

역대 로또 당첨 회차는 1회차\~10회차를 기준으로 한다.\
번호별 당첨 횟수는 아래와 같이 막대 그래프로 확인할 수 있다.

```{r}
#| label: load-package
#| include: false

library(httr)
library(rvest)
library(stringr)
```

```{r}
#| label: data-collection
#| warning: false
#| echo: false

start_no = 1
end_no = 10

lotto_data = list()

for (i in start_no:end_no){
  data_lotto = POST(
    url = "https://www.dhlottery.co.kr/gameResult.do?method=byWin",
    body = list(
      drwNo = as.character(i),
      dwrNoList = as.character(i)
    )
  )

data_lotto_html = data_lotto %>%  read_html()

win_numbers = data_lotto_html %>% 
  html_nodes('.num.win') %>% 
  html_text %>% 
  str_extract_all('\\d+') %>% 
  unlist()

lotto_data[[i]] = win_numbers

Sys.sleep(2)
}
```

```{r}
#| label: data-processing
#| warning: false
#| echo: false

library(dplyr)
library(tidyr)

lotto_df = do.call(rbind, lapply(lotto_data, function(x) as.data.frame(t(x), stringsAsFactors=FALSE)))

lotto_long <- lotto_df %>%
  pivot_longer(cols = everything(), names_to = "Position", values_to = "Number")

number_frequencies <- lotto_long %>%
  group_by(Number) %>%
  summarise(Frequency = n()) %>%
  arrange(as.numeric(Number))
```

```{r}
#| label: data-visualization
#| warning: false
#| echo: false

library(ggplot2)

ggplot(number_frequencies, aes(x = Number, y = Frequency)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_text(aes(label = Frequency), vjust = -0.5) +
  labs(title = "Frequency of Lotto Numbers", x = "Number", y = "Frequency") +
  theme_minimal()
```
